version: "3.3"
services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: deno_db
      MYSQL_USER: deno_user
      MYSQL_PASSWORD: deno_password
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - "./db:/var/lib/mysql"
