version: '3.8'

services:
  app:
    build:
      context: ../../../
      dockerfile: ./.containers/apps/api/Dockerfile.production
    environment:
      MYSQL_DATABASE: deno_db
      MYSQL_USERNAME: deno_user
      MYSQL_PASSWORD: deno_password
      MYSQL_HOST: db

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: deno_db
      MYSQL_USER: deno_user
      MYSQL_PASSWORD: deno_password
      MYSQL_RANDOM_ROOT_PASSWORD: "1"

volumes:
  mysql-data: